# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/myPro/cppPro/okRpc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/myPro/cppPro/okRpc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/myPro/cppPro/okRpc/CMakeFiles /root/myPro/cppPro/okRpc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/myPro/cppPro/okRpc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rpc_server

# Build rule for target.
rpc_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpc_server
.PHONY : rpc_server

# fast build rule for target.
rpc_server/fast:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/build
.PHONY : rpc_server/fast

RpcChannel.o: RpcChannel.cc.o
.PHONY : RpcChannel.o

# target to build an object file
RpcChannel.cc.o:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/RpcChannel.cc.o
.PHONY : RpcChannel.cc.o

RpcChannel.i: RpcChannel.cc.i
.PHONY : RpcChannel.i

# target to preprocess a source file
RpcChannel.cc.i:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/RpcChannel.cc.i
.PHONY : RpcChannel.cc.i

RpcChannel.s: RpcChannel.cc.s
.PHONY : RpcChannel.s

# target to generate assembly for a file
RpcChannel.cc.s:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/RpcChannel.cc.s
.PHONY : RpcChannel.cc.s

RpcServer.o: RpcServer.cc.o
.PHONY : RpcServer.o

# target to build an object file
RpcServer.cc.o:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/RpcServer.cc.o
.PHONY : RpcServer.cc.o

RpcServer.i: RpcServer.cc.i
.PHONY : RpcServer.i

# target to preprocess a source file
RpcServer.cc.i:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/RpcServer.cc.i
.PHONY : RpcServer.cc.i

RpcServer.s: RpcServer.cc.s
.PHONY : RpcServer.s

# target to generate assembly for a file
RpcServer.cc.s:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/RpcServer.cc.s
.PHONY : RpcServer.cc.s

RpcService.o: RpcService.cc.o
.PHONY : RpcService.o

# target to build an object file
RpcService.cc.o:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/RpcService.cc.o
.PHONY : RpcService.cc.o

RpcService.i: RpcService.cc.i
.PHONY : RpcService.i

# target to preprocess a source file
RpcService.cc.i:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/RpcService.cc.i
.PHONY : RpcService.cc.i

RpcService.s: RpcService.cc.s
.PHONY : RpcService.s

# target to generate assembly for a file
RpcService.cc.s:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/RpcService.cc.s
.PHONY : RpcService.cc.s

rpc.pb.o: rpc.pb.cc.o
.PHONY : rpc.pb.o

# target to build an object file
rpc.pb.cc.o:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc.pb.cc.o
.PHONY : rpc.pb.cc.o

rpc.pb.i: rpc.pb.cc.i
.PHONY : rpc.pb.i

# target to preprocess a source file
rpc.pb.cc.i:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc.pb.cc.i
.PHONY : rpc.pb.cc.i

rpc.pb.s: rpc.pb.cc.s
.PHONY : rpc.pb.s

# target to generate assembly for a file
rpc.pb.cc.s:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpc.pb.cc.s
.PHONY : rpc.pb.cc.s

rpcservice.pb.o: rpcservice.pb.cc.o
.PHONY : rpcservice.pb.o

# target to build an object file
rpcservice.pb.cc.o:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpcservice.pb.cc.o
.PHONY : rpcservice.pb.cc.o

rpcservice.pb.i: rpcservice.pb.cc.i
.PHONY : rpcservice.pb.i

# target to preprocess a source file
rpcservice.pb.cc.i:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpcservice.pb.cc.i
.PHONY : rpcservice.pb.cc.i

rpcservice.pb.s: rpcservice.pb.cc.s
.PHONY : rpcservice.pb.s

# target to generate assembly for a file
rpcservice.pb.cc.s:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/rpcservice.pb.cc.s
.PHONY : rpcservice.pb.cc.s

server.o: server.cc.o
.PHONY : server.o

# target to build an object file
server.cc.o:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/server.cc.o
.PHONY : server.cc.o

server.i: server.cc.i
.PHONY : server.i

# target to preprocess a source file
server.cc.i:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/server.cc.i
.PHONY : server.cc.i

server.s: server.cc.s
.PHONY : server.s

# target to generate assembly for a file
server.cc.s:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/server.cc.s
.PHONY : server.cc.s

sudoku.pb.o: sudoku.pb.cc.o
.PHONY : sudoku.pb.o

# target to build an object file
sudoku.pb.cc.o:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/sudoku.pb.cc.o
.PHONY : sudoku.pb.cc.o

sudoku.pb.i: sudoku.pb.cc.i
.PHONY : sudoku.pb.i

# target to preprocess a source file
sudoku.pb.cc.i:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/sudoku.pb.cc.i
.PHONY : sudoku.pb.cc.i

sudoku.pb.s: sudoku.pb.cc.s
.PHONY : sudoku.pb.s

# target to generate assembly for a file
sudoku.pb.cc.s:
	$(MAKE) -f CMakeFiles/rpc_server.dir/build.make CMakeFiles/rpc_server.dir/sudoku.pb.cc.s
.PHONY : sudoku.pb.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rpc_server"
	@echo "... RpcChannel.o"
	@echo "... RpcChannel.i"
	@echo "... RpcChannel.s"
	@echo "... RpcServer.o"
	@echo "... RpcServer.i"
	@echo "... RpcServer.s"
	@echo "... RpcService.o"
	@echo "... RpcService.i"
	@echo "... RpcService.s"
	@echo "... rpc.pb.o"
	@echo "... rpc.pb.i"
	@echo "... rpc.pb.s"
	@echo "... rpcservice.pb.o"
	@echo "... rpcservice.pb.i"
	@echo "... rpcservice.pb.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... sudoku.pb.o"
	@echo "... sudoku.pb.i"
	@echo "... sudoku.pb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

