// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sudoku.proto

#include "sudoku.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace sudoku {
class SudokuRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SudokuRequest>
      _instance;
} _SudokuRequest_default_instance_;
class SudokuResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SudokuResponse>
      _instance;
} _SudokuResponse_default_instance_;
}  // namespace sudoku
namespace protobuf_sudoku_2eproto {
static void InitDefaultsSudokuRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sudoku::_SudokuRequest_default_instance_;
    new (ptr) ::sudoku::SudokuRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sudoku::SudokuRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SudokuRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSudokuRequest}, {}};

static void InitDefaultsSudokuResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sudoku::_SudokuResponse_default_instance_;
    new (ptr) ::sudoku::SudokuResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sudoku::SudokuResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SudokuResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSudokuResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SudokuRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SudokuResponse.base);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::ServiceDescriptor* file_level_service_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sudoku::SudokuRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sudoku::SudokuRequest, checkerboard_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sudoku::SudokuResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sudoku::SudokuResponse, solved_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sudoku::SudokuResponse, checkerboard_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::sudoku::SudokuRequest)},
  { 6, -1, sizeof(::sudoku::SudokuResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::sudoku::_SudokuRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::sudoku::_SudokuResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "sudoku.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, file_level_service_descriptors);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014sudoku.proto\022\006sudoku\"%\n\rSudokuRequest\022"
      "\024\n\014checkerboard\030\001 \001(\t\"6\n\016SudokuResponse\022"
      "\016\n\006solved\030\001 \001(\010\022\024\n\014checkerboard\030\002 \001(\t2G\n"
      "\rSudokuService\0226\n\005Solve\022\025.sudoku.SudokuR"
      "equest\032\026.sudoku.SudokuResponseB\t\200\001\001\210\001\001\220\001"
      "\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 209);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "sudoku.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_sudoku_2eproto
namespace sudoku {

// ===================================================================

void SudokuRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SudokuRequest::kCheckerboardFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SudokuRequest::SudokuRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_sudoku_2eproto::scc_info_SudokuRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:sudoku.SudokuRequest)
}
SudokuRequest::SudokuRequest(const SudokuRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  checkerboard_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.checkerboard().size() > 0) {
    checkerboard_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.checkerboard_);
  }
  // @@protoc_insertion_point(copy_constructor:sudoku.SudokuRequest)
}

void SudokuRequest::SharedCtor() {
  checkerboard_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

SudokuRequest::~SudokuRequest() {
  // @@protoc_insertion_point(destructor:sudoku.SudokuRequest)
  SharedDtor();
}

void SudokuRequest::SharedDtor() {
  checkerboard_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SudokuRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SudokuRequest::descriptor() {
  ::protobuf_sudoku_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_sudoku_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SudokuRequest& SudokuRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_sudoku_2eproto::scc_info_SudokuRequest.base);
  return *internal_default_instance();
}


void SudokuRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:sudoku.SudokuRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  checkerboard_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool SudokuRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sudoku.SudokuRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string checkerboard = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_checkerboard()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->checkerboard().data(), static_cast<int>(this->checkerboard().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sudoku.SudokuRequest.checkerboard"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sudoku.SudokuRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sudoku.SudokuRequest)
  return false;
#undef DO_
}

void SudokuRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sudoku.SudokuRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string checkerboard = 1;
  if (this->checkerboard().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->checkerboard().data(), static_cast<int>(this->checkerboard().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sudoku.SudokuRequest.checkerboard");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->checkerboard(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:sudoku.SudokuRequest)
}

::google::protobuf::uint8* SudokuRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:sudoku.SudokuRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string checkerboard = 1;
  if (this->checkerboard().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->checkerboard().data(), static_cast<int>(this->checkerboard().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sudoku.SudokuRequest.checkerboard");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->checkerboard(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sudoku.SudokuRequest)
  return target;
}

size_t SudokuRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sudoku.SudokuRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string checkerboard = 1;
  if (this->checkerboard().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->checkerboard());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SudokuRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sudoku.SudokuRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const SudokuRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SudokuRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sudoku.SudokuRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sudoku.SudokuRequest)
    MergeFrom(*source);
  }
}

void SudokuRequest::MergeFrom(const SudokuRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sudoku.SudokuRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.checkerboard().size() > 0) {

    checkerboard_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.checkerboard_);
  }
}

void SudokuRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sudoku.SudokuRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SudokuRequest::CopyFrom(const SudokuRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sudoku.SudokuRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SudokuRequest::IsInitialized() const {
  return true;
}

void SudokuRequest::Swap(SudokuRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SudokuRequest::InternalSwap(SudokuRequest* other) {
  using std::swap;
  checkerboard_.Swap(&other->checkerboard_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SudokuRequest::GetMetadata() const {
  protobuf_sudoku_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_sudoku_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SudokuResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SudokuResponse::kSolvedFieldNumber;
const int SudokuResponse::kCheckerboardFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SudokuResponse::SudokuResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_sudoku_2eproto::scc_info_SudokuResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:sudoku.SudokuResponse)
}
SudokuResponse::SudokuResponse(const SudokuResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  checkerboard_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.checkerboard().size() > 0) {
    checkerboard_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.checkerboard_);
  }
  solved_ = from.solved_;
  // @@protoc_insertion_point(copy_constructor:sudoku.SudokuResponse)
}

void SudokuResponse::SharedCtor() {
  checkerboard_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  solved_ = false;
}

SudokuResponse::~SudokuResponse() {
  // @@protoc_insertion_point(destructor:sudoku.SudokuResponse)
  SharedDtor();
}

void SudokuResponse::SharedDtor() {
  checkerboard_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SudokuResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SudokuResponse::descriptor() {
  ::protobuf_sudoku_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_sudoku_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SudokuResponse& SudokuResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_sudoku_2eproto::scc_info_SudokuResponse.base);
  return *internal_default_instance();
}


void SudokuResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:sudoku.SudokuResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  checkerboard_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  solved_ = false;
  _internal_metadata_.Clear();
}

bool SudokuResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sudoku.SudokuResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool solved = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &solved_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string checkerboard = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_checkerboard()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->checkerboard().data(), static_cast<int>(this->checkerboard().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sudoku.SudokuResponse.checkerboard"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sudoku.SudokuResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sudoku.SudokuResponse)
  return false;
#undef DO_
}

void SudokuResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sudoku.SudokuResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool solved = 1;
  if (this->solved() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->solved(), output);
  }

  // string checkerboard = 2;
  if (this->checkerboard().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->checkerboard().data(), static_cast<int>(this->checkerboard().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sudoku.SudokuResponse.checkerboard");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->checkerboard(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:sudoku.SudokuResponse)
}

::google::protobuf::uint8* SudokuResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:sudoku.SudokuResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool solved = 1;
  if (this->solved() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->solved(), target);
  }

  // string checkerboard = 2;
  if (this->checkerboard().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->checkerboard().data(), static_cast<int>(this->checkerboard().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sudoku.SudokuResponse.checkerboard");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->checkerboard(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sudoku.SudokuResponse)
  return target;
}

size_t SudokuResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sudoku.SudokuResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string checkerboard = 2;
  if (this->checkerboard().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->checkerboard());
  }

  // bool solved = 1;
  if (this->solved() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SudokuResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sudoku.SudokuResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const SudokuResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SudokuResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sudoku.SudokuResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sudoku.SudokuResponse)
    MergeFrom(*source);
  }
}

void SudokuResponse::MergeFrom(const SudokuResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sudoku.SudokuResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.checkerboard().size() > 0) {

    checkerboard_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.checkerboard_);
  }
  if (from.solved() != 0) {
    set_solved(from.solved());
  }
}

void SudokuResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sudoku.SudokuResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SudokuResponse::CopyFrom(const SudokuResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sudoku.SudokuResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SudokuResponse::IsInitialized() const {
  return true;
}

void SudokuResponse::Swap(SudokuResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SudokuResponse::InternalSwap(SudokuResponse* other) {
  using std::swap;
  checkerboard_.Swap(&other->checkerboard_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(solved_, other->solved_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SudokuResponse::GetMetadata() const {
  protobuf_sudoku_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_sudoku_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

SudokuService::~SudokuService() {}

const ::google::protobuf::ServiceDescriptor* SudokuService::descriptor() {
  protobuf_sudoku_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sudoku_2eproto::file_level_service_descriptors[0];
}

const ::google::protobuf::ServiceDescriptor* SudokuService::GetDescriptor() {
  return descriptor();
}

void SudokuService::Solve(::google::protobuf::RpcController* controller,
                         const ::sudoku::SudokuRequest*,
                         ::sudoku::SudokuResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method Solve() not implemented.");
  done->Run();
}

void SudokuService::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), protobuf_sudoku_2eproto::file_level_service_descriptors[0]);
  switch(method->index()) {
    case 0:
      Solve(controller,
             ::google::protobuf::down_cast<const ::sudoku::SudokuRequest*>(request),
             ::google::protobuf::down_cast< ::sudoku::SudokuResponse*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& SudokuService::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::sudoku::SudokuRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::google::protobuf::Message& SudokuService::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::sudoku::SudokuResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

SudokuService_Stub::SudokuService_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
SudokuService_Stub::SudokuService_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
SudokuService_Stub::~SudokuService_Stub() {
  if (owns_channel_) delete channel_;
}

void SudokuService_Stub::Solve(::google::protobuf::RpcController* controller,
                              const ::sudoku::SudokuRequest* request,
                              ::sudoku::SudokuResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace sudoku
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::sudoku::SudokuRequest* Arena::CreateMaybeMessage< ::sudoku::SudokuRequest >(Arena* arena) {
  return Arena::CreateInternal< ::sudoku::SudokuRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::sudoku::SudokuResponse* Arena::CreateMaybeMessage< ::sudoku::SudokuResponse >(Arena* arena) {
  return Arena::CreateInternal< ::sudoku::SudokuResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
